#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml
contact:
    path:       /{_locale}/
    controller: App\Controller\KampController::index
    requirements:
        _locale: en|fr|de|nl
